
example_1 = """
When you are looking up at the stars and planets at night, do you ever wander what is going on up there. Well what if I said that there was a chance to go visit the planet Venus. Yes, there is many dangers on Venus, but there is so much to explore too; like how Venus is the most like Earth when it comes to shape and size, the gases and temperture, and the curious of how Venus looks like now.
When you think of Venus, what do you think of? Do you think of the heat or the size? Well, when scienetist think of Venus they "[often] referred to as Earth's "twin", Venus is the cloese planet to Earth in terms of density and size, and occasionally the closet in distance too". So, becasue of how close it looks in shape and size, you have to have though in your mind of, what else does it have in common.
When you think of dangerous gases and temperture, what this the things that you think of? Do you think of hot summer day or the gases in the air? Well, on Venus "[a] thick atmosphere of almost 97 percent carbon dioxide blankets Venus. Even more challenging are the clouds of highly corrosive sulfuris acid in Venus's atmoshpere. In the planet's surface, tempertures average over 800 degrees Fahrenheit, and the atmospheris pressure is 90 times greater than we experience on our own planet". Eventhough, it could be life theathing, there are scientist that want to do test and collect gases and ect to do studies. They want to do studies because they want to learn some much more about Venus.
When you think of how Venus looks like, do you think of craters and the sign of no life? Well, you be somewhat correct because it has a rocky surface, and it looks like valleys, mountain and craters. Although "[long] ago, Venus was probably covered largely with oceans and could have supported various forms of life, just like Earth". Since, there was a possible that there was life forms and etc, scientist want to see if there was some kind of life living up there, but then got exstinted or somethings else happened to them.
So, to rap this all up, scientist know the danger of explore Venus, but sometime you have to do thing that are danger to learn new things. People alway talk about wanting to explore different planets, but they never do it. Yes, there are going to be opsolcules in the way, and there are going to be dangerous things we have do to go there, but it will be worth it in end. Nevertheless, there was forms of life on Venus in the past, why not have life on Venus again.
"""
example_2 = """
Hi, i'm Isaac, i'm going to be writing about how this face on Mars is a natural landform or if there is life on Mars that made it. The story is about how NASA took a picture of Mars and a face was seen on the planet. NASA doesn't know if the landform was created by life on Mars, or if it is just a natural landform. On my perspective, I think that the face is a natural landform because I dont think that there is any life on Mars. In these next few paragraphs, I'll be talking about how I think that is is a natural landform\n\nI think that the face is a natural landform because there is no life on Mars that we have descovered yet. If life was on Mars, we would know by now. The reason why I think it is a natural landform because, nobody live on Mars in order to create the figure. It says in paragraph 9, "It's not easy to target Cydonia," in which he is saying that its not easy to know if it is a natural landform at this point. In all that they're saying, its probably a natural landform.\n\nPeople thought that the face was formed by alieans because they thought that there was life on Mars. though some say that life on Mars does exist, I think that there is no life on Mars.\n\nIt says in paragraph 7, on April 5, 1998, Mars Global Surveyor flew over Cydonia for the first time. Michael Malin took a picture of Mars with his Orbiter Camera, that the face was a natural landform. Everyone who thought it was made by alieans even though it wasn't, was not satisfied. I think they were not satisfied because they have thought since 1976 that it was really formed by alieans.\n\nThough people were not satified about how the landform was a natural landform, in all, we new that alieans did not form the face. I would like to know how the landform was formed. we know now that life on Mars doesn't exist.
"""